seed : 0

n_layers : 6
block_size : 2
input_dim : 696
hidden_size : 100
in_channels : 64
n_classes : 30

batch_size : 2048
n_epochs : 3000 
lr : 1e-3
num_workers : 4
fp16 : True

X_fn : './data/bacteria-id/preprocessed/X_reference.npy'
y_fn : './data/bacteria-id/preprocessed/y_reference.npy'
